CREATE TABLE dbo.Chats(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	SenderId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(Id) ON DELETE CASCADE,
	Content NVARCHAR(4000) NOT NULL,
	SendTime DATETIME NOT NULL)
	;
CREATE TABLE dbo.Users(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Name NVARCHAR(500) NOT NULL UNIQUE,
	ColorOfName NVARCHAR(500) )

SELECT * FROM dbo.Chats


SELECT * FROM dbo.Users

TRUNCATE TABLE dbo.Users

DELETE FROM dbo.Users

DROP TABLE dbo.Chats

DROP TABLE dbo.Users

